# Generated by Django 3.2.5 on 2022-03-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorIsbnNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
